project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub Course name"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Python from ipynb example"
          href: notebooks/01a-fundamentals.html
        - text: "R from qmd example"
          href: notebooks/01b_exampleRcontent.html
        - text: "Markdown from md example"
          href: notebooks/01c_exampleMDcontent.html
  cookie-consent: 
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false


